### Pengujian Titik Akhir API Autentikasi

# 1. Mendaftarkan Pengguna Baru
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "Panji Angkasa",
  "email": "panjangkasa@gmail.com",
  "password": "123123"
}

###

# 2. Masuk Pengguna (Login)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "panjangkasa@gmail.com",
  "password": "123123"
}

###

# 3. Keluar Pengguna (Logout)
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYW5qYW5na2FzYUBnbWFpbC5jb20iLCJpYXQiOjE3NzMyOTY0OTQsImV4cCI6MTc3MzM4Mjg5NH0.w7nD0k8LFevj1IJ1GHR3eHXca1fWQ5yQNjjkk8XXDDQ
