spring.application.name=Aplikasi Keuangan
spring.datasource.url=jdbc:postgresql://localhost:5432/akuntansiku_db
spring.datasource.username=postgres
spring.datasource.password=password_database_kamu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT Configuration

jwt.secret=gilakRahasiaBangetINI!!!
jwt.expiration.ms=86400000 # Contoh: 86400000 ms = 24 Jam
